### ISSUE TITLE
How to print `sync::cache` state

### ISSUE THREAD

**Issue by kakoc** [al8n/stretto#26]
Suppose I have a `sync::Cache<_, _>` and I'd like to display its content(for example for debugging purposes). How can I do that? I didn't find any way.

**Comment by al8n** [comment]
Hi, which stats you want to print? Currently, this crate does not provide any iter for users to view all of the data in the cache.

**Comment by kakoc** [comment]
I'd like to see `key: value` pairs

**Comment by al8n** [comment]
If you want to see how many `key: value` pairs are in the cache, I can add the functionality. But if you want to see something like `key1: value1` `key2: value2`, and etc, we seem to cannot do it because of the cache design. But you can implement a custom `CacheCallback`. I think it can give you the equivalent functionality.
